# Generated by Django 4.1.5 on 2023-01-23 06:39

from django.db import migrations, models
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('age', models.PositiveIntegerField()),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', phone_field.models.PhoneField(blank=True, help_text='Contact phone number', max_length=31)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(default='OH', max_length=100)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(default='43701', max_length=5)),
                ('profile_created_date', models.DateField(auto_now_add=True)),
                ('profile_updated_date', models.DateField(auto_now=True)),
            ],
        ),
    ]
