# Generated by Django 4.1.5 on 2023-01-25 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Crud_pro', '0002_rename_langauage_developer_developer_langauage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='developer',
            name='developer_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_developer', to=settings.AUTH_USER_MODEL),
        ),
    ]
